# Generated by Django 5.0 on 2023-12-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('secondname', models.CharField(max_length=200)),
                ('thirdname', models.CharField(max_length=200)),
            ],
        ),
    ]
